shop-test/src/main/java/by/epamlab/inttraining/entity/Account.java
package by.epamlab.inttraining.entity;

import by.epamlab.inttraining.service.CurrentUser;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "account")
public class Account implements Serializable, CurrentUser {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String login;

    private String password;

    private String email;

    private String role;

    //bi-directional many-to-one association to Order
    @OneToMany(mappedBy = "account")
    private List<Order> orders;

    public Account() {
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public String getDescription() {
        return login;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public List<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public Order addOrder(Order order) {
        getOrders().add(order);
        order.setAccount(this);

        return order;
    }

    public Order removeOrder(Order order) {
        getOrders().remove(order);
        order.setAccount(null);
        return order;
    }

}

shop-test/src/main/webapp/WEB-INF/JSP/fragment/aside.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<div class="visible-xs-block xs-option-container">
    <a class="pull-left" data-toggle="collapse" href="#productCatalog">Product catalog<span class="caret"></span></a>
</div>
<div id="productCatalog" class="panel panel-default collapse">
    <div class="panel-heading"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Product catalog</div>
    <div class="list-group">
        <c:forEach var="category" items="${categories}">
            <a href="/products${category.url}"
               class="list-group-item ${selectedCategoryUrl == category.url ? 'active' : ''}">${category.name}</a>
        </c:forEach>
    </div>
</div>

shop-test/src/main/webapp/WEB-INF/JSP/fragment/footer.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<div class="container">
    <p class="text-center">Created by - Stas Nesteruk &copy; Shop, 2019</p>
</div>

shop-test/src/main/webapp/WEB-INF/JSP/fragment/header.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#shop-navbar"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/products">Shop</a>
        </div>
        <div class="collapse navbar-collapse" id="shop-navbar">
            <ul class="nav navbar-nav navbar-right">
                <c:choose>
                    <c:when test="${not empty CURRENT_USER}">
                        <li>
                            <form action="/search" class="navbar-form search">
                                <div id="findProducts" class="form-group">
                                    <input type="text" name="query" class="form-control" placeholder="Search for..."
                                           value="${searchQuery}">
                                </div>
                            </form>
                        </li>
                        <li><a>Welcome, ${CURRENT_USER.description}</a></li>
                        <li><a href="/my-orders">My orders</a></li>
                        <c:if test="${CURRENT_USER.role == 'admin'}">
                            <li><a href="/edit" ${EDIT_MODE == 'ON' ? 'style="font-weight: bold"' : ''}>Edit mode</a>
                            </li>
                        </c:if>
                        <li><a href="/sign-out">Sign out</a></li>
                    </c:when>
                    <c:otherwise>
                        <li><a href="/login">Sign in</a></li>
                        <li><a href="/sign-up">Sign up</a></li>
                    </c:otherwise>
                </c:choose>
                <li id="currentShoppingCart" class="dropdown ${not empty CURRENT_SHOPPING_CART ? '': 'hidden'}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <i class="fa fa-shopping-cart" area-hidden="true"></i> Shopping cart(<span
                            class="total-count">${CURRENT_SHOPPING_CART.totalCount}</span>)
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu shopping-cart-desc">
                        Total count: <span class="total-count">${CURRENT_SHOPPING_CART.totalCount}</span><br>
                        <hr class="hr">
                        Total cost: <span class="total-cost">${CURRENT_SHOPPING_CART.totalCost}</span><br>
                        <hr class="hr">
                        <a href="/shopping-cart" class="btn btn-default btn-block">View cart</a>
                    </div>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>